# Site settings
title: SALESHORSES
#email: john.lamar@gmail.com
description: "Get to the horse!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: Benioff
github_username:  Saleshorses

# Build settings
markdown: kramdown
permalink: pretty
